# Generated by Django 3.1.4 on 2026-05-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('forte', 'Forte'), ('ruina', 'Ruína'), ('museu', 'Museu'), ('igreja', 'Igreja'), ('marco', 'Marco histórico'), ('casarao', 'Casarão')], max_length=50, verbose_name='Categoria')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período histórico')),
                ('imagens', models.JSONField(blank=True, default=list, verbose_name='Imagens (cores)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
    ]
