# Generated by Django 3.1.4 on 2026-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricao_norte', models.FloatField(default=-22.5, verbose_name='Limite Norte')),
                ('restricao_sul', models.FloatField(default=-33.8, verbose_name='Limite Sul')),
                ('restricao_leste', models.FloatField(default=-48.0, verbose_name='Limite Leste')),
                ('restricao_oeste', models.FloatField(default=-57.7, verbose_name='Limite Oeste')),
                ('centro_lat', models.FloatField(default=-27.0, verbose_name='Centro Lat')),
                ('centro_lng', models.FloatField(default=-52.0, verbose_name='Centro Lng')),
                ('zoom_inicial', models.IntegerField(default=7, verbose_name='Zoom inicial')),
                ('zoom_minimo', models.IntegerField(default=6, verbose_name='Zoom mínimo')),
                ('poligono', models.JSONField(default=list, verbose_name='Polígono da região')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Mapa',
            },
        ),
    ]
